### ISSUE TITLE
Ceiling hanging signs do not work

### ISSUE THREAD

**Issue by tastybento** [BentoBoxWorld/Warps#127]
### Expected behavior

Ceiling hanging signed should work as warp signs.

### Observed/Actual behavior

```
[09:14:04] [Server thread/WARN]: [BentoBox] Task #40693 for BentoBox v2.0.0-SNAPSHOT-LOCAL generated an exception
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_20_R3.block.impl.CraftCeilingHangingSign cannot be cast to class org.bukkit.block.data.type.Sign (org.bukkit.craftbukkit.v1_20_R3.block.impl.CraftCeilingHangingSign and org.bukkit.block.data.type.Sign are in unnamed module of loader java.net.URLClassLoader @5c29bfd)
	at world.bentobox.warps.managers.WarpSignsManager.warpPlayer(WarpSignsManager.java:441) ~[Warps-1.13.0.jar:?]
	at world.bentobox.warps.commands.WarpCommand.lambda$execute$3(WarpCommand.java:71) ~[Warps-1.13.0.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-377]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.4.jar:git-Paper-377]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1639) ~[paper-1.20.4.jar:git-Paper-377]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.4.jar:git-Paper-377]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1518) ~[paper-1.20.4.jar:git-Paper-377]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[paper-1.20.4.jar:git-Paper-377]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[paper-1.20.4.jar:git-Paper-377]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Steps/models to reproduce

1. Place a ceiling hanging sign
2. Make sure your level is high enough
3. Write "[welcome]" on the sign - it should go green
4. Try to warp to it.

### BentoBox version

2.0.0-SNAPSHOT

**Comment by tastybento** [comment]
Fixed in latest release.
