### ISSUE TITLE
Warps being deleted after server restart

### ISSUE THREAD

**Issue by piotrskibapl** [BentoBoxWorld/Warps#70]
**Description**
I encounter a bug that results in all warps deletion after server restart.

**Steps to reproduce the behavior:**
1. Create an island warp
2. Restart the server
3. Join the server from an other account and try to teleport to the previously created warp
4. The warp doesn't exist

**Expected behavior**
The user should be properly teleported to the island.

**Server Information:**
Paper 1.15.2
BentoBox 1.11.1
Warps 1.9.0

**Additional context**
Console stacktrace:

> [09:08:19] [Server thread/ERROR]: Could not pass event SignChangeEvent to BentoBox v1.11.1
java.lang.NullPointerException: null
	at world.bentobox.warps.WarpSignsManager.saveWarpList(WarpSignsManager.java:255) ~[?:?]
	at world.bentobox.warps.WarpSignsManager.addWarp(WarpSignsManager.java:101) ~[?:?]
	at world.bentobox.warps.WarpSignsListener.addSign(WarpSignsListener.java:177) ~[?:?]
	at world.bentobox.warps.WarpSignsListener.onSignWarpCreate(WarpSignsListener.java:115) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor597.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-105]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-105]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-105]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:559) ~[patched_1.15.2.jar:git-Paper-105]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2582) ~[patched_1.15.2.jar:git-Paper-105]
	at net.minecraft.server.v1_15_R1.PacketPlayInUpdateSign.a(SourceFile:44) ~[patched_1.15.2.jar:git-Paper-105]
	at net.minecraft.server.v1_15_R1.PacketPlayInUpdateSign.a(SourceFile:10) ~[patched_1.15.2.jar:git-Paper-105]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-105]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-105]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-105]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-105]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-105]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[patched_1.15.2.jar:git-Paper-105]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[patched_1.15.2.jar:git-Paper-105]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-105]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1102) ~[patched_1.15.2.jar:git-Paper-105]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-105]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

**Comment by piotrskibapl** [comment]
It looks like this bug is not present anymore on Warps 1.9.3 version, so I'll close the issue.
