### ISSUE TITLE
SignChangeEvent Error

### ISSUE THREAD

**Issue by silvasky54** [BentoBoxWorld/Warps#71]
**Description**
Everytime a warp sign is created an error occurs in the console and the sign does not change. Addon still considers them warp signs as they show in the gui but after a restart they are all deleted.

**Steps to reproduce the behavior:**
1. Create warp sign
2. Notice welcome line did not change.
3. Check gui, see warp.
4. Check console, see error.
5. Restart server.
6. All warps deleted.

**Expected behavior**
Warp signs should change [Welcome] to green. Warps should stay in gui after restart. No errors in console.

**Screenshots**
https://imgur.com/a/ZAauAUi

**Server Information:**
Do `bbox version` in the console and paste the result here:
02.04 17:11:04 [Server] Server thread/INFO Running SPIGOT 1.15.2.
02.04 17:11:04 [Server] Server thread/INFO BentoBox version: 1.12.0
02.04 17:11:04 [Server] Server thread/INFO Database: SQLITE
02.04 17:11:04 [Server] Server thread/INFO Loaded Game Worlds:
02.04 17:11:04 [Server] Server thread/INFO sky_world (sky): Overworld, Nether, The End
02.04 17:11:04 [Server] Server thread/INFO Loaded Addons:
02.04 17:11:04 [Server] Server thread/INFO Biomes 1.6.0.1-SNAPSHOT-b151 (ENABLED)
02.04 17:11:04 [Server] Server thread/INFO BSkyBlock 1.12.0 (ENABLED)
02.04 17:11:04 [Server] Server thread/INFO ControlPanel 1.7.0-SNAPSHOT-#9 (ENABLED)
02.04 17:11:04 [Server] Server thread/INFO DimensionalTrees 1.6.0-SNAPSHOT-b80 (ENABLED)
02.04 17:11:04 [Server] Server thread/INFO Level 1.9.4-SNAPSHOT-b345 (ENABLED)
02.04 17:11:04 [Server] Server thread/INFO MagicCobblestoneGenerator 1.9.0-SNAPSHOT-b95 (ENABLED)
02.04 17:11:04 [Server] Server thread/INFO TwerkingForTrees 1.1.2 (ENABLED)
02.04 17:11:04 [Server] Server thread/INFO Warps 1.9.3-SNAPSHOT-b222 (ENABLED)

**Additional context**
Error:
```
02.04 16:58:00 [Server] Server thread/ERROR Could not pass event SignChangeEvent to BentoBox v1.12.0
02.04 16:58:00 [Server] INFO org.bukkit.event.EventException: null
02.04 16:58:00 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[custom.jar:git-Spigot-8faa8b4-3d61a85]
02.04 16:58:00 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[custom.jar:git-Spigot-8faa8b4-3d61a85]
02.04 16:58:00 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:541) ~[custom.jar:git-Spigot-8faa8b4-3d61a85]
02.04 16:58:00 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:528) ~[custom.jar:git-Spigot-8faa8b4-3d61a85]
02.04 16:58:00 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2392) ~[custom.jar:git-Spigot-8faa8b4-3d61a85]
02.04 16:58:00 [Server] INFO at net.minecraft.server.v1_15_R1.PacketPlayInUpdateSign.a(SourceFile:44) ~[custom.jar:git-Spigot-8faa8b4-3d61a85]
02.04 16:58:00 [Server] INFO at net.minecraft.server.v1_15_R1.PacketPlayInUpdateSign.a(SourceFile:10) ~[custom.jar:git-Spigot-8faa8b4-3d61a85]
02.04 16:58:00 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[custom.jar:git-Spigot-8faa8b4-3d61a85]
02.04 16:58:00 [Server] INFO at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [custom.jar:git-Spigot-8faa8b4-3d61a85]
02.04 16:58:00 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [custom.jar:git-Spigot-8faa8b4-3d61a85]
02.04 16:58:00 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [custom.jar:git-Spigot-8faa8b4-3d61a85]
02.04 16:58:00 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [custom.jar:git-Spigot-8faa8b4-3d61a85]
02.04 16:58:00 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918) [custom.jar:git-Spigot-8faa8b4-3d61a85]
02.04 16:58:00 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911) [custom.jar:git-Spigot-8faa8b4-3d61a85]
02.04 16:58:00 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [custom.jar:git-Spigot-8faa8b4-3d61a85]
02.04 16:58:00 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:895) [custom.jar:git-Spigot-8faa8b4-3d61a85]
02.04 16:58:00 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828) [custom.jar:git-Spigot-8faa8b4-3d61a85]
02.04 16:58:00 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
02.04 16:58:00 [Server] INFO Caused by: java.lang.NullPointerException
02.04 16:58:00 [Server] INFO at world.bentobox.warps.WarpSignsManager.saveWarpList(WarpSignsManager.java:255) ~[?:?]
02.04 16:58:00 [Server] INFO at world.bentobox.warps.WarpSignsManager.addWarp(WarpSignsManager.java:101) ~[?:?]
02.04 16:58:00 [Server] INFO at world.bentobox.warps.listeners.WarpSignsListener.addSign(WarpSignsListener.java:194) ~[?:?]
02.04 16:58:00 [Server] INFO at world.bentobox.warps.listeners.WarpSignsListener.onSignWarpCreate(WarpSignsListener.java:132) ~[?:?]
02.04 16:58:00 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_211]
02.04 16:58:00 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_211]
02.04 16:58:00 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_211]
02.04 16:58:00 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_211]
02.04 16:58:00 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[custom.jar:git-Spigot-8faa8b4-3d61a85]
02.04 16:58:00 [Server] INFO ... 17 more

02.04 16:58:00 [Server] INFO 	... 17 more
```

**Comment by tastybento** [comment]
Thanks. This should be fixed in the latest snapshot release now.
