### ISSUE TITLE
is warps gui won't show: WarpListEvent may only be triggered synchronously

### ISSUE THREAD

**Issue by x1p** [BentoBoxWorld/Warps#93]
**Description**

is warps does nothing. No gui will appear

**Steps to reproduce the behavior:**
1. Use warp 1.10.2 build 278
2. Execute /is warps
3. See error

**Expected behavior**

Show the warps GUI

**Screenshots**

**Server Information:**
Do `bbox version` in the console and paste the result here:
[19:54:07 INFO]: Running PURPUR 1.16.4.
[19:54:07 INFO]: BentoBox version: 1.15.6-SNAPSHOT-b1944
[19:54:07 INFO]: Database: JSON
[19:54:07 INFO]: Loaded Game Worlds:
[19:54:07 INFO]: bskyblock_world (BSkyBlock): Overworld, Nether, The End
[19:54:07 INFO]: Loaded Addons:
[19:54:07 INFO]: Biomes 1.14.0-SNAPSHOT-b198 (ENABLED)
[19:54:07 INFO]: BSkyBlock 1.14.3 (ENABLED)
[19:54:07 INFO]: Challenges 0.8.4-SNAPSHOT-b438 (ENABLED)
[19:54:07 INFO]: Level 2.5.1 (ENABLED)
[19:54:07 INFO]: Limits 1.15.2 (ENABLED)
[19:54:07 INFO]: MagicCobblestoneGenerator 2.3.0-SNAPSHOT-b202 (ENABLED)
[19:54:07 INFO]: Warps 1.10.2-SNAPSHOT-b278 (ENABLED)

**Additional context**

Error:
```
[19:47:06 INFO]: Player_x1p_123 issued server command: /is warps
[19:47:06 WARN]: [BentoBox] Plugin BentoBox v1.15.6-SNAPSHOT-b1944 generated an exception while executing task 1354973
java.lang.IllegalStateException: WarpListEvent may only be triggered synchronously.
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:595) ~[patched_1.16.4.jar:git-Purpur-936]
at world.bentobox.warps.WarpSignsManager.getSortedWarps(WarpSignsManager.java:159) ~[?:?]
at world.bentobox.warps.WarpPanelManager.buildPanel(WarpPanelManager.java:80) ~[?:?]
at world.bentobox.warps.WarpPanelManager.lambda$showWarpPanel$5(WarpPanelManager.java:73) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Purpur-936]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58) ~[patched_1.16.4.jar:git-Purpur-936]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.4.jar:git-Purpur-936]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by wellnesscookie** [comment]
Same problem, same error log overhere

**Comment by tastybento** [comment]
Should be fixed in latest snapshot. Build 280.

**Comment by tastybento** [comment]
This is **not** fixed. There are still async issues. I'll work on this tomorrow.

**Comment by wellnesscookie** [comment]
Hi, 

Are we safe to use the newest dev build and consider this fixed?
Or do you require us to test it before uploading to production server?

**Comment by n54b** [comment]
0 update for the moment ... need to wait :( @wellnesscookie could you send me your version or does it work? :)

**Comment by tastybento** [comment]
This should be fixed in the latest CI build.

**Comment by tastybento** [comment]
Dev builds always need testing by yourself before using in production. They may be unstable. Releases are more stable and have more testing. Thanks for your understanding.
